-- Fase 92: historial de palomeos y comentarios del ABC.
--
-- abc_avance conserva el estado actual de cada casilla. Estas tablas
-- agregan los eventos y comentarios sin reemplazar ese modelo.

create table if not exists public.abc_avance_historial (
  id                  bigint generated by default as identity primary key,
  kwid                text not null references public.abc_asesores(kwid) on delete cascade,
  tema_id             smallint not null references public.abc_temas(id) on delete cascade,
  completado          boolean not null,
  marcado_por         uuid references auth.users(id) on delete set null,
  marcado_por_nombre  text not null default 'Usuario no identificado',
  marcado_en          timestamptz not null default now()
);

alter table public.abc_avance_historial
  add column if not exists marcado_por_nombre text not null default 'Usuario no identificado';

create index if not exists abc_avance_historial_kwid_fecha_idx
  on public.abc_avance_historial (kwid, marcado_en desc);
create index if not exists abc_avance_historial_fecha_idx
  on public.abc_avance_historial (marcado_en desc);

alter table public.abc_avance_historial enable row level security;

drop policy if exists "abc_avance_historial_select" on public.abc_avance_historial;
create policy "abc_avance_historial_select" on public.abc_avance_historial
  for select to authenticated using (public.is_staff_or_above());

create or replace function public.abc_registrar_avance_historial()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text;
begin
  if tg_op <> 'INSERT'
     and old.completado is not distinct from new.completado
     and old.marcado_por is not distinct from new.marcado_por
     and old.marcado_en is not distinct from new.marcado_en then
    return new;
  end if;

  if tg_op = 'INSERT' or tg_op = 'UPDATE' then
    select coalesce(
      nullif(trim(coalesce(p.nombre, '') || ' ' || coalesce(p.apellido, '')), ''),
      p.email
    )
      into v_nombre
      from public.profiles p
     where p.id = new.marcado_por;

    insert into public.abc_avance_historial (
      kwid, tema_id, completado, marcado_por, marcado_por_nombre, marcado_en
    ) values (
      new.kwid,
      new.tema_id,
      new.completado,
      new.marcado_por,
      coalesce(v_nombre, 'Registro previo'),
      new.marcado_en
    );
  end if;
  return new;
end;
$$;

drop trigger if exists abc_avance_historial_trigger on public.abc_avance;
create trigger abc_avance_historial_trigger
  after insert or update on public.abc_avance
  for each row execute function public.abc_registrar_avance_historial();

-- Conserva la fecha que ya existe en abc_avance como primer registro
-- visible para los palomeos anteriores a esta migracion.
insert into public.abc_avance_historial (
  kwid, tema_id, completado, marcado_por, marcado_por_nombre, marcado_en
)
select
  a.kwid,
  a.tema_id,
  a.completado,
  a.marcado_por,
  coalesce(
    nullif(trim(coalesce(p.nombre, '') || ' ' || coalesce(p.apellido, '')), ''),
    p.email,
    'Registro previo'
  ),
  a.marcado_en
from public.abc_avance a
left join public.profiles p on p.id = a.marcado_por
where not exists (
  select 1
    from public.abc_avance_historial h
   where h.kwid = a.kwid
     and h.tema_id = a.tema_id
     and h.completado = a.completado
     and h.marcado_en = a.marcado_en
     and h.marcado_por is not distinct from a.marcado_por
);

create table if not exists public.abc_comentarios (
  id                  bigint generated by default as identity primary key,
  kwid                text not null references public.abc_asesores(kwid) on delete cascade,
  comentario          text not null check (char_length(btrim(comentario)) between 1 and 1000),
  creado_por          uuid references auth.users(id) on delete set null,
  creado_por_nombre   text not null default 'Usuario no identificado',
  creado_en           timestamptz not null default now()
);

alter table public.abc_comentarios
  add column if not exists creado_por_nombre text not null default 'Usuario no identificado';

create index if not exists abc_comentarios_kwid_fecha_idx
  on public.abc_comentarios (kwid, creado_en desc);

alter table public.abc_comentarios enable row level security;

drop policy if exists "abc_comentarios_select" on public.abc_comentarios;
create policy "abc_comentarios_select" on public.abc_comentarios
  for select to authenticated using (public.is_staff_or_above());

drop policy if exists "abc_comentarios_insert" on public.abc_comentarios;
create policy "abc_comentarios_insert" on public.abc_comentarios
  for insert to authenticated with check (public.is_staff_or_above());

create or replace function public.abc_preparar_comentario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text;
begin
  if auth.uid() is null then
    raise exception 'Se requiere una sesion para guardar comentarios';
  end if;

  new.creado_por := auth.uid();
  new.comentario := btrim(coalesce(new.comentario, ''));
  new.creado_en := now();

  select coalesce(
    nullif(trim(coalesce(p.nombre, '') || ' ' || coalesce(p.apellido, '')), ''),
    p.email
  )
    into v_nombre
    from public.profiles p
   where p.id = auth.uid();

  new.creado_por_nombre := coalesce(v_nombre, 'Usuario no identificado');
  return new;
end;
$$;

drop trigger if exists abc_comentarios_prepare on public.abc_comentarios;
create trigger abc_comentarios_prepare
  before insert on public.abc_comentarios
  for each row execute function public.abc_preparar_comentario();
